// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import edu.wpi.first.hal.FRCNetComm.tInstances;
import edu.wpi.first.hal.FRCNetComm.tResourceType;
import edu.wpi.first.hal.HAL;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.SlewRateLimiter;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.subsystems.Climber;
import frc.robot.subsystems.DriveTrain;
import frc.robot.subsystems.Intake;
import frc.robot.subsystems.Shooter;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in 
 * the project.
 */
public class Robot extends TimedRobot {
    private static final String kRightAuto = "Right Auto";
    private static final String kLeftAuto = "Left Auto";
    private static final String kMiddleAuto = "Middle Auto"; 
    private String m_autoSelected;
    private SendableChooser<String> auto_chooser = new SendableChooser<>();
    private final SlewRateLimiter m_xspeedLimiter = new SlewRateLimiter(3);
    private final SlewRateLimiter m_yspeedLimiter = new SlewRateLimiter(3);
    private final SlewRateLimiter m_rotLimiter = new SlewRateLimiter(3);
    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DriveTrain driveTrain;
    public static Intake intake;
    public static Shooter shooter;
    public static Climber climber;
    NetworkTableEntry centerXEntry;
    double aSpeed;
    double bSpeed;
    double ySpeed;
    double xSpeed;
    boolean twoMotors;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
        auto_chooser.addDefault("Middle Auto", kMiddleAuto);
        auto_chooser.addOption("Right Auto", kRightAuto);
        auto_chooser.addOption("Left Auto", kLeftAuto);
        SmartDashboard.putData("Auto Selection", auto_chooser);
        SmartDashboard.putNumber("aSpeed", 0.0);
        SmartDashboard.putNumber("bSpeed", 0.0);
        SmartDashboard.putNumber("ySpeed", 0.0);
        SmartDashboard.putNumber("xSpeed", 0.0);
        SmartDashboard.putBoolean("Two Motors", false);
        NetworkTableInstance  inst = NetworkTableInstance.getDefault();
        NetworkTable table = inst.getTable("pi");
        aSpeed = 0.0;
        bSpeed = 0.0;
        ySpeed = 0.0;
        xSpeed = 0.0;
      
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrain = new DriveTrain();
        intake = new Intake();
        shooter = new Shooter();
        climber = new Climber();
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        HAL.report(tResourceType.kResourceType_Framework, tInstances.kFramework_RobotBuilder);

        // Add commands to Autonomous Sendable Chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){

    }
   

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
       m_autoSelected = auto_chooser.getSelected();
       
       System.out.println("Auto selected: " + m_autoSelected);
       
       switch (m_autoSelected){

           case "Middle Auto":

           case "Left Auto":

           case "Right Auto":

       }
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
        
    }

    @Override
    public void teleopInit() {

    }
        
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
      

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        aSpeed = SmartDashboard.getNumber("aSpeed", 0.0);
        bSpeed = SmartDashboard.getNumber("bSpeed", 0.0);
        ySpeed = SmartDashboard.getNumber("ySpeed", 0.0);
        xSpeed = SmartDashboard.getNumber("xSpeed", 0.0);
        twoMotors = SmartDashboard.getBoolean("Two Motors", false);
        Scheduler.getInstance().run();
        System.out.println(centerXEntry);
        final double xSpeed = -m_xspeedLimiter.calculate(oi.getLeftJoystickX());
        final double ySpeed = -m_yspeedLimiter.calculate(oi.getLeftJoystickY());
        final double rot = m_rotLimiter.calculate(oi.getRightJoystickX());
        SmartDashboard.putNumber("xSpeed", xSpeed);
        SmartDashboard.putNumber("ySpeed", ySpeed);
        SmartDashboard.putNumber("rotSpeed", rot);
      
        driveTrain.runMecanumDrive(xSpeed, ySpeed, rot);
        
        
        // if (oi.getAButton()){
        //     intake.runIntake(aSpeed, twoMotors);
        //     System.out.println("Running at " + aSpeed + "% speed.");
        // } else  if (oi.getBButton()){
        //     intake.runIntake(bSpeed, twoMotors);
        //     System.out.println("Running at " + bSpeed + "% speed.");
        // } else if (oi.getYButton()){
        //     intake.runIntake(ySpeed, twoMotors);
        //     System.out.println("Running at " + ySpeed + "% speed.");
        // } else if (oi.getXButton()){
        //     intake.runIntake(xSpeed, twoMotors);
        //     System.out.println("Running at " + xSpeed + "% speed.");
        // } else {
        //     intake.runIntake(0, false);
        // }
        
       
    }
    @Override
    public void testPeriodic() {
        if(oi.getAButton()){
            driveTrain.runRightRear(1);
        } else {
            driveTrain.runRightRear(0);
        }
        if(oi.getBButton()){
            driveTrain.runrightFront(1);
        } else {
            driveTrain.runrightFront(0);
        }
        if(oi.getYButton()){
            driveTrain.runLeftRear(1);
        } else {
            driveTrain.runLeftRear(0);
        }
        if(oi.getXButton()){
            driveTrain.runLeftFront(-1);
        } else {
            driveTrain.runLeftFront(0);
        }
    }
   
}
