// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.controls;

import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    
    public XboxControl xboxController;
    public Joystick fightStick;



    public OI() {
        fightStick = new Joystick(1);
        xboxController = new XboxControl(0);

    }

    public XboxControl Xbox() {
        return xboxController;
    }

    public Joystick getFightStick() {
    return fightStick;
    }

// Xbox Controls




// FightStick Controls 
public double getFSVerticalStick(){
    return fightStick.getRawAxis(1);
}
public double getFSHorizontalStick(){
    return fightStick.getRawAxis(0);
}
public boolean getFSXButton(){
    return fightStick.getRawButtonPressed(2);
}
public boolean getFSAButton(){
    return fightStick.getRawButtonPressed(0);
}
public boolean getFSYButton(){
    return fightStick.getRawButtonPressed(3);
}
public boolean getFSBButton(){
    return fightStick.getRawButtonPressed(1);
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}



