// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.controls;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    
    private XboxControl xboxController;
    private FightStick fightStick;

    public OI() {
        fightStick = new FightStick(1);
        xboxController = new XboxControl(0);
    }
    public XboxControl xBox() {
        return xboxController;
    }
    public FightStick fightStick() {
        return fightStick;
    }
    

}



