

package frc.robot.subsystems.intake;

import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


public class Intake {

    
    // private final VictorSP leftIntake;
    // // private final VictorSP rightIntake;
    // double aSpeed;
    // double bSpeed;
    // double ySpeed;
    // double xSpeed;
    // boolean twoMotors;

    // public Intake() {
    //     SmartDashboard.putNumber("aSpeed", 0.0);
    //     SmartDashboard.putNumber("bSpeed", 0.0);
    //     SmartDashboard.putNumber("ySpeed", 0.0);
    //     SmartDashboard.putNumber("xSpeed", 0.0);
    //     SmartDashboard.putBoolean("Two Motors", false);
        
    //     leftIntake = new VictorSP(1);
    //     // rightIntake = new VictorSP(2);
    //     // leftIntake.enableDeadbandElimination(true);
    //     // rightIntake.enableDeadbandElimination(true);

    //     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    //     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    // }

   

    // @Override
    // public void periodic() {
    //     aSpeed = SmartDashboard.getNumber("aSpeed", 0.0);
    //     bSpeed = SmartDashboard.getNumber("bSpeed", 0.0);
    //     ySpeed = SmartDashboard.getNumber("ySpeed", 0.0);
    //     xSpeed = SmartDashboard.getNumber("xSpeed", 0.0);
    //     twoMotors = SmartDashboard.getBoolean("Two Motors", false);
        
    //        // if (oi.getAButton()){
    //     //     intake.runIntake(aSpeed, twoMotors);
    //     //     System.out.println("Running at " + aSpeed + "% speed.");
    //     // } else  if (oi.getBButton()){
    //     //     intake.runIntake(bSpeed, twoMotors);
    //     //     System.out.println("Running at " + bSpeed + "% speed.");
    //     // } else if (oi.getYButton()){
    //     //     intake.runIntake(ySpeed, twoMotors);
    //     //     System.out.println("Running at " + ySpeed + "% speed.");
    //     // } else if (oi.getXButton()){
    //     //     intake.runIntake(xSpeed, twoMotors);
    //     //     System.out.println("Running at " + xSpeed + "% speed.");
    //     // } else {
    //     //     intake.runIntake(0, false);
    //     // }

    // }

    // public void runIntake(double speed, boolean twoMotors){
    //     if(twoMotors){
    //         leftIntake.setSpeed(speed);
    //         // rightIntake.setSpeed(speed);
    //     } else { 
    //         leftIntake.setSpeed(speed);
            
    //     }

       
    
  

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

